package com.example.demo.model;

import jakarta.persistence.*;
import java.time.Instant;

/**
 * PUBLIC_INTERFACE
 * Score entity representing a game session score for Click Quest.
 *
 * Fields:
 * - id: Primary key (generated)
 * - playerName: Name of the player (non-null)
 * - score: Total points scored (non-null)
 * - durationMs: Duration of the game session in milliseconds (non-null)
 * - createdAt: When the score entry was created (non-null)
 *
 * Includes basic indexes on playerName, score, and createdAt for common query patterns.
 */
@Entity
@Table(
        name = "scores",
        indexes = {
                @Index(name = "idx_scores_player_name", columnList = "player_name"),
                @Index(name = "idx_scores_score", columnList = "score"),
                @Index(name = "idx_scores_created_at", columnList = "created_at")
        }
)
public class Score {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "player_name", nullable = false, length = 100)
    private String playerName;

    @Column(name = "score", nullable = false)
    private Integer score;

    @Column(name = "duration_ms", nullable = false)
    private Long durationMs;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * PUBLIC_INTERFACE
     * Default constructor required by JPA.
     */
    public Score() {
        // JPA
    }

    /**
     * PUBLIC_INTERFACE
     * Convenience constructor.
     */
    public Score(String playerName, Integer score, Long durationMs, Instant createdAt) {
        this.playerName = playerName;
        this.score = score;
        this.durationMs = durationMs;
        this.createdAt = createdAt;
    }

    @PrePersist
    protected void onCreate() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    // PUBLIC_INTERFACE
    public Long getId() {
        /** Returns the autogenerated ID. */
        return id;
    }

    // PUBLIC_INTERFACE
    public String getPlayerName() {
        /** Returns the player's name. */
        return playerName;
    }

    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    // PUBLIC_INTERFACE
    public Integer getScore() {
        /** Returns the score value. */
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    // PUBLIC_INTERFACE
    public Long getDurationMs() {
        /** Returns the session duration in milliseconds. */
        return durationMs;
    }

    public void setDurationMs(Long durationMs) {
        this.durationMs = durationMs;
    }

    // PUBLIC_INTERFACE
    public Instant getCreatedAt() {
        /** Returns the creation timestamp. */
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}
